In [89]:
import torch
#二维卷积无padding
def corr2d(Data,Kernel,Stride):
    Y=torch.zeros(((Data.shape[0]-Kernel.shape[0]+1)//(Stride[0]),(Data.shape[1]-Kernel.shape[1]+1)//(Stride[1])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j]=(Data[i*Stride[0]:i*Stride[0]+Kernel.shape[0],j*Stride[1]:j*Stride[1]+Kernel.shape[1]]*Kernel).sum()
    return Y
# 测试案例
#corr2d(torch.tensor([[1,2,3],[4,5,6],[5,6,7]]),torch.tensor([[1,2],[2,3]]),Stride=(1,1))
#二维卷积有padding
#def corr2d_pad(Data=(a,b),Kernel=(c,d),Padding=(e,f),Stride=(g,h)):
def corr2d_pad(Data,Kernel,Padding,Stride):
    Data=torch.concatenate((torch.zeros((Padding[0],Data.shape[1])),Data,torch.zeros((Padding[0],Data.shape[1]))),axis=0)
    Data=torch.concatenate((torch.zeros((Data.shape[0],Padding[1])),Data,torch.zeros((Data.shape[0],Padding[1]))),axis=1)
    Y=torch.zeros(((Data.shape[0]-Kernel.shape[0]+1)//(Stride[0]),(Data.shape[1]-Kernel.shape[1]+1)//(Stride[1])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j]=(Data[i*Stride[0]:i*Stride[0]+Kernel.shape[0],j*Stride[1]:j*Stride[1]+Kernel.shape[1]]*Kernel).sum()
    return Y
# 测试案例
#corr2d_pad(torch.tensor([[1,2,3],[4,5,6],[5,6,7]]),torch.tensor([[1,2],[2,3]]),(1,1),(1,1))
#三维卷积无padding
def corr3d(Data,Kernel,Stride):
    Y=torch.zeros(((Data.shape[0]-Kernel.shape[0]+1)//(Stride[0]),(Data.shape[1]-Kernel.shape[1]+1)//(Stride[1]),(Data.shape[2]-Kernel.shape[2]+1)//(Stride[2])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(Y.shape[2]):
                Y[i,j,k]=(Data[i*Stride[0]:i*Stride[0]+Kernel.shape[0],j*Stride[1]:j*Stride[1]+Kernel.shape[1],k*Stride[2]:k*Stride[2]+Kernel.shape[2]]*Kernel).sum()
    return Y
# 测试案例
#corr3d(Data=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]),Kernel=torch.tensor([[[1,2],[1,1]],[[1,-1],[-1,2]]]),Stride=(1,1,1))
#三维卷积有padding
def corr3d_pad(Data,Kernel,Padding,Stride):
    Data=torch.concatenate((torch.zeros((Padding[0],Data.shape[1],Data.shape[2])),Data,torch.zeros((Padding[0],Data.shape[1],Data.shape[2]))),axis=0)
    Data=torch.concatenate((torch.zeros((Data.shape[0],Padding[1],Data.shape[2])),Data,torch.zeros((Data.shape[0],Padding[1],Data.shape[2]))),axis=1)
    Data=torch.concatenate((torch.zeros((Data.shape[0],Data.shape[1],Padding[2])),Data,torch.zeros((Data.shape[0],Data.shape[1],Padding[2]))),axis=2)
    Y=torch.zeros(((Data.shape[0]-Kernel.shape[0]+1)//(Stride[0]),(Data.shape[1]-Kernel.shape[1]+1)//(Stride[1]),(Data.shape[2]-Kernel.shape[2]+1)//(Stride[2])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(Y.shape[2]):
                Y[i,j,k]=(Data[i*Stride[0]:i*Stride[0]+Kernel.shape[0],j*Stride[1]:j*Stride[1]+Kernel.shape[1],k*Stride[2]:k*Stride[2]+Kernel.shape[2]]*Kernel).sum()
    return Y
# 测试案例
#corr3d_pad(Data=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]),Kernel=torch.tensor([[[1,2],[1,1]],[[1,-1],[-1,2]]]),Padding=(0,0,0),Stride=(1,1,1))
####################################################
#池化
#二维池化无padding
#def pool2d(Data,Mode='max,'avg'):
def pool2d(Data,Kernel,mode,Stride):
    Y=torch.zeros(((Data.shape[0]-Kernel[0]+1)//(Stride[0]),(Data.shape[1]-Kernel[1]+1)//(Stride[1])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j]=Data[i*Stride[0]:i*Stride[0]+Kernel[0],j*Stride[1]:j*Stride[1]+Kernel[1]].max()
            elif mode=='mean':
                Y[i,j]=Data[i*Stride[0]:i*Stride[0]+Kernel[0],j*Stride[1]:j*Stride[1]+Kernel[1]].mean()
    return Y
#二维池化有padding
def pool2d_pad(Data,Kernel,mode,Padding,Stride):
    Data=torch.concatenate((torch.zeros((Padding[0],Data.shape[1])),Data,torch.zeros((Padding[0],Data.shape[1]))),axis=0)
    Data=torch.concatenate((torch.zeros((Data.shape[0],Padding[1])),Data,torch.zeros((Data.shape[0],Padding[1]))),axis=1)
    Y=torch.zeros(((Data.shape[0]-Kernel[0]+1)//(Stride[0]),(Data.shape[1]-Kernel[1]+1)//(Stride[1])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode=='max':
                Y[i,j]=Data[i*Stride[0]:i*Stride[0]+Kernel[0],j*Stride[1]:j*Stride[1]+Kernel[1]].max()
            elif mode=='mean':
                Y[i,j]=Data[i*Stride[0]:i*Stride[0]+Kernel[0],j*Stride[1]:j*Stride[1]+Kernel[1]].mean()
    return Y  
#三维池化无padding
def pool3d(Data,Kernel,mode):
    Y=torch.zeros((Data.shape[0]-Kernel[0]+1,Data.shape[1]-Kernel[1]+1,Data.shape[2]-Kernel[2]+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(Y.shape[2]):
                if mode=='max':
                    Y[i,j,k]=Data[i:i+Kernel[0],j:j+Kernel[1],k:k+Kernel[2]].max()
                elif mode=='mean':
                    Y[i,j,k]=Data[i:i+Kernel[0],j:j+Kernel[1],k:k+Kernel[2]].mean()
    return Y
#三维池化有padding
def pool3d_pad(Data,Kernel,mode,Padding,Stride):
    Data=torch.concatenate((torch.zeros((Padding[0],Data.shape[1],Data.shape[2])),Data,torch.zeros((Padding[0],Data.shape[1],Data.shape[2]))),axis=0)
    Data=torch.concatenate((torch.zeros((Data.shape[0],Padding[1],Data.shape[2])),Data,torch.zeros((Data.shape[0],Padding[1],Data.shape[2]))),axis=1)
    Data=torch.concatenate((torch.zeros((Data.shape[0],Data.shape[1],Padding[2])),Data,torch.zeros((Data.shape[0],Data.shape[1],Padding[2]))),axis=2)
    Y=torch.zeros(((Data.shape[0]-Kernel[0]+1)//(Stride[0]),(Data.shape[1]-Kernel[1]+1)//(Stride[1]),(Data.shape[2]-Kernel[2]+1)//(Stride[2])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            for k in range(Y.shape[2]):
                if mode=='max':
                    Y[i,j,k]=Data[i*Stride[0]:i*Stride[0]+Kernel[0],j*Stride[1]:j*Stride[1]+Kernel[1],k*Stride[2]:k*Stride[2]+Kernel[2]].max()
                elif mode=='mean':
                    Y[i,j,k]=Data[i*Stride[0]:i*Stride[0]+Kernel[0],j*Stride[1]:j*Stride[1]+Kernel[1],k*Stride[2]:k*Stride[2]+Kernel[2]].mean()
    return Y
# 测试案例
#pool2d(torch.tensor([[1.,2,3],[4,5,6],[5,6,7.]]),(2,3),'mean')
#pool2d_pad(torch.tensor([[1.,2,3],[4,5,6],[5,6,7]]),(2,2),'mean',(1,1),(1,1))
#pool3d(Data=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]),Kernel=(2,2,2),mode='max')
#pool3d_pad(Data=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]),Kernel=(2,2,2),mode='max',Padding=(0,0,0),Stride=(1,1,1))

In [93]:
corr3d(Data=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]),Kernel=torch.tensor([[[1,2],[1,1]],[[1,-1],[-1,2]]]),Stride=(1,1,1))

tensor([[[16., 22.]]])

In [97]:
corr3d_pad(Data=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]),Kernel=torch.tensor([[[1,2],[1,1]],[[1,-1],[-1,2]]]),Padding=(0,0,0),Stride=(1,1,1))

tensor([[[16., 22.]]])

In [79]:
#定义卷积层操作无padding
#下面是二维样本特征时多样本多输出的卷积层
def convnet_2d(Data,Kernel,bias,Padding,Stride):
    Y=torch.zeros((Data.shape[0],Kernel.shape[0],(Data.shape[1]-Kernel.shape[1]+2*Padding[0]+1)//(Stride[0]),(Data.shape[2]-Kernel.shape[2]+2*Padding[1]+1)//(Stride[1])))
    #第几个样本
    for i in range(Y.shape[0]):
        #第几个输出内核
        for j in range(Y.shape[1]):
            Y[i,j,:,:]=corr2d_pad(Data[i,:,:].reshape(Data.shape[1:]),Kernel[j,:,:].reshape(Kernel.shape[1:]),Padding,Stride)
            Y[i,j,:,:]+=bias[j]        
    Y=1/(1+torch.exp(-Y))
    return Y
#测试
#Kernel=torch.randn((4,3,3),requires_grad=True)
#bias=torch.randn((Kernel.shape[0],1),requires_grad=True)
#convnet_2d(torch.randn(1,7,7),Kernel,bias,Padding=(1,1),Stride=(1,1))
#下面是三维样本特征时多样本多输出的卷积层
def convnet_3d(Data,Kernel,bias,Padding,Stride):
    Y=torch.zeros((Data.shape[0],Kernel.shape[0],(Data.shape[1]-Kernel.shape[1]+2*Padding[0]+1)//(Stride[0]),(Data.shape[2]-Kernel.shape[2]+2*Padding[1]+1)//(Stride[1]),(Data.shape[3]-Kernel.shape[3]+2*Padding[2]+1)//(Stride[2])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j,:,:,:]=corr3d_pad(Data[i,:,:,:].reshape(Data.shape[1:]),Kernel[j,:,:,:].reshape(Kernel.shape[1:]),Padding,Stride)
            Y[i,j,:,:,:]+=bias[j]
    Y=1/(1+torch.exp(-Y))
    return Y
#测试
#Kernel=torch.randn((4,3,3,3),requires_grad=True)
#bias=torch.randn((Kernel.shape[0],1),requires_grad=True)
#convnet_3d(torch.randn(1,7,7,7),Kernel,bias,Padding=(1,1,1),Stride=(1,1,1))
#下面是二维样本特征多样本多输出的汇聚层。
def poolnet_2d(Data,Kernel,mode,Padding,Stride):
    Y=torch.zeros((Data.shape[0],Data.shape[1],(Data.shape[2]-Kernel[0]+2*Padding[0]+1)//(Stride[0]),(Data.shape[3]-Kernel[1]+2*Padding[1]+1)//(Stride[1])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j,:,:]=pool2d_pad(Data[i,j,:,:].reshape(Data.shape[2:]),Kernel,mode,Padding,Stride)
    return Y
#测试
#Kernel=torch.randn((4,3,3),requires_grad=True)
#bias=torch.randn((Kernel.shape[0],1),requires_grad=True)
#Y=convnet_2d(torch.randn(1,7,7),Kernel,bias,Padding=(1,1),Stride=(1,1))
#print(Y)
#Z=poolnet_2d(Y,Kernel=(3,3),mode='max',Padding=(1,1),Stride=(1,1))
#print(Z)
#下面是三维样本特征多样本多输出的汇聚层
def poolnet_3d(Data,Kernel,mode,Padding,Stride):
    Y=torch.zeros((Data.shape[0],Data.shape[1],(Data.shape[2]-Kernel[0]+2*Padding[0]+1)//(Stride[0]),(Data.shape[3]-Kernel[1]+2*Padding[1]+1)//(Stride[1]),(Data.shape[4]-Kernel[2]+2*Padding[2]+1)//(Stride[2])))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j,:,:,:]=pool3d_pad(Data[i,j,:,:,:].reshape(Data.shape[2:]),Kernel,mode,Padding,Stride)
    return Y
#测试
#Kernel=torch.randn((4,3,3,3),requires_grad=True)
#bias=torch.randn((Kernel.shape[0],1),requires_grad=True)
#Y=convnet_3d(torch.randn(1,7,7,7),Kernel,bias,Padding=(1,1,1),Stride=(1,1,1))
#print(Y)
#Z=poolnet_3d(Y,Kernel=(3,3,3),mode='max',Padding=(1,1,1),Stride=(1,1,1))
#print(Z)

In [82]:
Kernel=torch.randn((4,3,3,3),requires_grad=True)
bias=torch.randn((Kernel.shape[0],1),requires_grad=True)
Y=convnet_3d(torch.randn(1,7,7,7),Kernel,bias,Padding=(1,1,1),Stride=(1,1,1))
print(Y)
Z=poolnet_3d(Y,Kernel=(3,3,3),mode='max',Padding=(1,1,1),Stride=(1,1,1))
print(Z)

tensor([[[[[4.2703e-01, 3.0811e-01, 8.2895e-01,  ..., 2.5966e-01,
            9.6171e-01, 3.7893e-01],
           [4.4822e-01, 9.6114e-01, 9.9219e-01,  ..., 5.5801e-01,
            7.7938e-01, 6.7513e-01],
           [1.8379e-02, 5.7729e-01, 7.5762e-02,  ..., 9.5847e-01,
            6.7444e-03, 4.5325e-02],
           ...,
           [9.8336e-01, 5.2515e-01, 9.8252e-01,  ..., 1.6955e-01,
            4.1651e-01, 3.6497e-02],
           [2.6899e-01, 9.9652e-01, 5.1926e-02,  ..., 5.8690e-01,
            8.7093e-01, 4.8052e-01],
           [2.2633e-02, 1.3136e-01, 1.7376e-02,  ..., 6.0629e-01,
            2.3777e-01, 5.5856e-01]],

          [[1.0327e-01, 2.1420e-01, 1.1890e-01,  ..., 9.0163e-01,
            9.8107e-02, 7.2509e-01],
           [9.7923e-01, 7.6323e-02, 7.2366e-01,  ..., 9.3179e-01,
            4.1466e-02, 1.3912e-01],
           [9.8436e-01, 9.9762e-01, 9.4347e-01,  ..., 9.6269e-01,
            9.8295e-01, 7.3895e-02],
           ...,
           [9.7294e-01, 1.5966e-02, 4.7

In [60]:
print(Kernel,bias)

tensor([[[ 0.4984,  1.4733,  0.3368],
         [-0.0781,  1.4690,  0.1219],
         [ 0.0144, -0.0055,  0.3415]],

        [[-0.1570,  0.8827, -0.0291],
         [-0.2214,  2.0122, -1.2865],
         [-2.8076,  0.6688, -0.0180]],

        [[-2.0035, -1.9294, -0.6290],
         [ 1.0588,  1.2516,  1.5535],
         [ 0.6034, -0.7063, -0.1388]],

        [[-0.2145,  1.1761,  1.1970],
         [-0.8008, -1.0112, -0.2242],
         [-1.0511,  0.2420, -1.2773]]], requires_grad=True) tensor([[-3.8033],
        [ 0.0159],
        [ 2.3508],
        [ 0.7002]], requires_grad=True)
